return {
	"mfussenegger/nvim-dap",
	config = function()
		local dap = require("dap")
		local dap_widgets = require("dap.ui.widgets")
		vim.keymap.set("n", "<F5>", function()
			dap.continue()
		end)
		vim.keymap.set("n", "<F8>", function()
			dap.step_over()
		end)
		vim.keymap.set("n", "<F7>", function()
			dap.step_into()
		end)
		vim.keymap.set("n", "<leader>b", function()
			dap.toggle_breakpoint()
		end)
		vim.keymap.set("n", "<leader>B", function()
			dap.set_breakpoint()
		end)
		vim.keymap.set("n", "<Leader>cb", function()
			dap.set_breakpoint(vim.fn.input("Breakpoint condition: "))
		end)
		vim.keymap.set("n", "<Leader>lp", function()
			dap.set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
		end)
		vim.keymap.set("n", "<Leader>dr", function()
			dap.repl.open()
		end)
		vim.keymap.set("n", "<Leader>dl", function()
			dap.run_last()
		end)
		vim.keymap.set({ "n", "v" }, "<Leader>dh", function()
			dap_widgets.hover()
		end)
		vim.keymap.set({ "n", "v" }, "<Leader>dp", function()
			dap_widgets.preview()
		end)
		vim.keymap.set("n", "<Leader>df", function()
			dap_widgets.centered_float(dap_widgets.frames)
		end)
		vim.keymap.set("n", "<Leader>ds", function()
			dap_widgets.centered_float(dap_widgets.scopes)
		end)

		vim.api.nvim_set_hl(0, "red", { fg = "#ff4500" })
		vim.api.nvim_set_hl(0, "blue", { fg = "#00ffff" })
		vim.api.nvim_set_hl(0, "green", { fg = "#9ece6a" })
		vim.api.nvim_set_hl(0, "yellow", { fg = "#FFFF00" })
		vim.api.nvim_set_hl(0, "orange", { fg = "#f09000" })

		vim.fn.sign_define("DapBreakpoint", { text = "", texthl = "red" })
		vim.fn.sign_define("DapBreakpointCondition", { text = "", texthl = "blue" })
		vim.fn.sign_define("DapLogPoint", { text = "", texthl = "yellow" })
		vim.fn.sign_define("DapStopped", { text = "", texthl = "green" })
		vim.fn.sign_define("DapBreakpointRejected", { text = "", texthl = "orange" })
	end,
}
